version: '3'
services:
    qobuz:
        image: docker-qobuz
        ports:
            - 5000:5080
        environment:
            - QOBUZNAME=name@gmail.com
            - QOBUZPASS=password123
        restart: unless-stopped
